stages:
  - check

info-ubuntu:
  stage: check
  image: ubuntu:24.04
  script:
    - apt update
    - apt install -y --no-install-recommends lsb-release inxi dmidecode psmisc systemd perl
    - ./vmt.sh
